version: 2.1

jobs:
  build-deploy-production:
    machine:
      image: ubuntu-2204:2022.04.2
    resource_class: large

    steps:
      - checkout

      - run:
          name: Check Docker daemon status
          command: docker version
      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USERNAME/pop-ku:latest --build-arg NEXT_PUBLIC_POCKETBASE_URL=$NEXT_PUBLIC_POCKETBASE_URL .

      # Push Docker image to registry
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/pop-ku:latest
      - run:
          name: "Trigger Portainer"
          command: curl --location --request POST $PT_TRIGGER_API

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-deploy-production:
          filters:
            branches:
              only:
                - develop
      # - build-deploy-development:
      #     filters:
      #       branches:
      #         only:
      #           - develop